name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Daily update
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN || secrets.GITHUB_TOKEN }}
          user: naitiktuxx
          template: classic
          base: header, activity, community, repositories
          config_timezone: Asia/Kolkata
          
          # Green Dots Calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          # Activity & Streaks
          plugin_habits: yes
          plugin_habits_facts: yes
          
          # LeetCode Stats (Screenshot jaisa)
          plugin_leetcode: yes
          plugin_leetcode_user: naitiktuxx # Agar LeetCode username alag hai to yahan change karein
          plugin_leetcode_sections: solved, overview
